<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Authorizer.Domain\Authorizer.Domain.csproj" />
    <ProjectReference Include="..\Authorizer.GrpcCommon\Authorizer.GrpcCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.84.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Authorizer.GrpcClient</PackageId>
    <Version>1.0.2</Version>
    <Authors>Joseph Melberg</Authors>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
